eureka:
  client:
    registerWithEureka: true
    serviceUrl: 
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    instance:
      hostname: localhost
    healthcheck:
      enabled: true
